name: Daily Python Script Scheduler (Ubuntu)

on:
  schedule:
    - cron: '5 0 * * *'  # Runs daily at 12:01 AM UTC
  workflow_dispatch:       # Optional manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi  # Use Bash syntax to check if file exists

      - name: Run script and store output/logs
        run: |
          python test/count_numbers.py > output.txt 2>&1  # Redirect both stdout and stderr to output.txt
