name: Daily Python Script Scheduler (Windows)

on:
  schedule:
    - cron: '16 0 * * *'  # Runs daily at 12:01 AM UTC
  workflow_dispatch:       # Optional manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: windows-2022  # Explicitly use Windows Server 2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { pip install -r requirements.txt }  # Correct PowerShell syntax

      - name: Run script and store output/logs
        run: |
          python test/count_numbers.py > output.txt 2> log.txt  # Redirects stdout to output.txt and stderr to log.txt
